package de.dittner.testmyself.utils {
import de.dittner.testmyself.model.Device;

public class Values {
	public function Values() {}

	public static const PT1:Number = Device.factor;
	public static const PT2:Number = 2 * Device.factor;
	public static const PT3:Number = 3 * Device.factor;
	public static const PT4:Number = 4 * Device.factor;
	public static const PT5:Number = 5 * Device.factor;
	public static const PT6:Number = 6 * Device.factor;
	public static const PT7:Number = 7 * Device.factor;
	public static const PT8:Number = 8 * Device.factor;
	public static const PT9:Number = 9 * Device.factor;
	public static const PT10:Number = 10 * Device.factor;
	public static const PT11:Number = 11 * Device.factor;
	public static const PT12:Number = 12 * Device.factor;
	public static const PT13:Number = 13 * Device.factor;
	public static const PT14:Number = 14 * Device.factor;
	public static const PT15:Number = 15 * Device.factor;
	public static const PT16:Number = 16 * Device.factor;
	public static const PT17:Number = 17 * Device.factor;
	public static const PT18:Number = 18 * Device.factor;
	public static const PT19:Number = 19 * Device.factor;
	public static const PT20:Number = 20 * Device.factor;
	public static const PT21:Number = 21 * Device.factor;
	public static const PT22:Number = 22 * Device.factor;
	public static const PT23:Number = 23 * Device.factor;
	public static const PT24:Number = 24 * Device.factor;
	public static const PT25:Number = 25 * Device.factor;
	public static const PT26:Number = 26 * Device.factor;
	public static const PT27:Number = 27 * Device.factor;
	public static const PT28:Number = 28 * Device.factor;
	public static const PT29:Number = 29 * Device.factor;
	public static const PT30:Number = 30 * Device.factor;
	public static const PT31:Number = 31 * Device.factor;
	public static const PT32:Number = 32 * Device.factor;
	public static const PT33:Number = 33 * Device.factor;
	public static const PT34:Number = 34 * Device.factor;
	public static const PT35:Number = 35 * Device.factor;
	public static const PT36:Number = 36 * Device.factor;
	public static const PT37:Number = 37 * Device.factor;
	public static const PT38:Number = 38 * Device.factor;
	public static const PT39:Number = 39 * Device.factor;
	public static const PT40:Number = 40 * Device.factor;
	public static const PT42:Number = 42 * Device.factor;
	public static const PT50:Number = 50 * Device.factor;
	public static const PT52:Number = 52 * Device.factor;
	public static const PT55:Number = 55 * Device.factor;
	public static const PT60:Number = 60 * Device.factor;
	public static const PT68:Number = 68 * Device.factor;
	public static const PT70:Number = 70 * Device.factor;
	public static const PT72:Number = 72 * Device.factor;
	public static const PT80:Number = 80 * Device.factor;
	public static const PT87:Number = 87 * Device.factor;
	public static const PT90:Number = 90 * Device.factor;
	public static const PT100:Number = 100 * Device.factor;
	public static const PT110:Number = 110 * Device.factor;
	public static const PT113:Number = 113 * Device.factor;
	public static const PT118:Number = 118 * Device.factor;
	public static const PT120:Number = 120 * Device.factor;
	public static const PT125:Number = 125 * Device.factor;
	public static const PT130:Number = 130 * Device.factor;
	public static const PT140:Number = 140 * Device.factor;
	public static const PT150:Number = 150 * Device.factor;
	public static const PT160:Number = 160 * Device.factor;
	public static const PT170:Number = 170 * Device.factor;
	public static const PT180:Number = 180 * Device.factor;
	public static const PT200:Number = 200 * Device.factor;
	public static const PT220:Number = 220 * Device.factor;
	public static const PT250:Number = 250 * Device.factor;
	public static const PT280:Number = 280 * Device.factor;
	public static const PT300:Number = 300 * Device.factor;
	public static const PT330:Number = 330 * Device.factor;
	public static const PT350:Number = 350 * Device.factor;
	public static const PT400:Number = 400 * Device.factor;
	public static const PT420:Number = 420 * Device.factor;
	public static const PT450:Number = 450 * Device.factor;
	public static const PT500:Number = 500 * Device.factor;
	public static const PT550:Number = 550 * Device.factor;
}
}
